'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, BarChart3, CalendarDays, FileSpreadsheet, PiggyBank, Plus, Wallet } from 'lucide-react'
import { MESES_2026 } from '../../lib/modelo-orcamento'

const nav=[{href:'/controle',label:'Controle',icon:BarChart3},{href:'/lancamentos',label:'Lançamentos',icon:ArrowDownLeft},{href:'/contas',label:'Contas',icon:Wallet},{href:'/investimentos',label:'Investimentos',icon:PiggyBank},{href:'/homologacao',label:'Homologação',icon:FileSpreadsheet}]
const contas=['Conta Corrente','Poupança','Investimentos']
export default function LancamentosPage(){const [mes,setMes]=useState<(typeof MESES_2026)[number]>('Set/26');const [conta,setConta]=useState('Conta Corrente');return <div className="app"><aside className="sidebar"><div className="brand"><div className="brandMark">R$</div><div><strong>Orçamento</strong><span>Familiar</span></div></div><nav>{nav.map(n=>{const Icon=n.icon;return <Link key={n.href} href={n.href} className={n.href==='/lancamentos'?'active':''}><Icon size={17}/>{n.label}</Link>})}</nav><div className="sideBottom"><small>LANÇAMENTOS</small><p>Registre as movimentações na conta em que aconteceram.</p></div></aside><main className="content"><header className="top"><div><p className="eyebrow">ORÇAMENTO FAMILIAR</p><h1>Lançamentos</h1><p className="muted">Movimentações por conta · {mes}</p></div><div className="month controlMonth"><CalendarDays size={16}/><select value={mes} onChange={e=>setMes(e.target.value as typeof mes)}>{MESES_2026.map(m=><option key={m}>{m}</option>)}</select></div></header><section className="panel launchHeader"><div><h2>Conta de lançamento</h2><p>Escolha a conta onde o dinheiro entrou ou saiu.</p></div><div className="accountTabs">{contas.map(c=><button key={c} className={conta===c?'selected':''} onClick={()=>setConta(c)}><Wallet size={15}/>{c}</button>)}</div></section><section className="cards controlCards"><article><div className="cardIcon income"><ArrowDownLeft size={19}/></div><div><span>Entradas</span><strong>—</strong><small>Na conta selecionada</small></div></article><article><div className="cardIcon expense"><ArrowUpRight size={19}/></div><div><span>Saídas</span><strong>—</strong><small>Despesas da família</small></div></article><article><div className="cardIcon balance"><Wallet size={19}/></div><div><span>Saldo movimentado</span><strong>—</strong><small>{conta}</small></div></article></section><section className="panel"><div className="panelHead"><div><h2>Movimentações de {conta}</h2><p>Receitas, despesas e transferências registradas nesta conta.</p></div><button className="primary"><Plus size={16}/>Novo lançamento</button></div><div className="empty">Nenhum lançamento em {mes}.<br/>Use <strong>Novo lançamento</strong> para registrar uma movimentação.</div></section><section className="grid moduleBottom"><article className="panel"><div className="panelHead"><div><h2>Regra do lançamento</h2><p>Conta e natureza são informações diferentes.</p></div></div><p className="moduleNote">A conta identifica onde ocorreu a movimentação. A natureza identifica se é receita, despesa ou transferência. Transferências entre contas não entram no resultado familiar.</p></article><article className="panel"><div className="panelHead"><div><h2>Próxima etapa</h2><p>Estrutura preparada para integração.</p></div></div><p className="moduleNote">Depois de validar os campos, os lançamentos alimentarão automaticamente o controle de despesas e o fluxo de caixa da primeira tela.</p></article></section></main></div>}
