'use client'

import Link from 'next/link'
import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowDownLeft, BarChart3, FileSpreadsheet, Lightbulb, Pencil, Percent, PiggyBank, Save, TrendingDown, TrendingUp, Upload, Users, Wallet, X } from 'lucide-react'
import * as XLSX from 'xlsx'
import { MESES_2026 } from '../../lib/modelo-orcamento'

const meses = [...MESES_2026]
const STORAGE_KEY = 'orcamento-familiar-homologacao-2026'
type Dados = Record<string, number[]>
const moeda = (v:number) => v === 0 ? '—' : v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2,maximumFractionDigits:2})
const pct = (v:number) => `${v.toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}%`
const nav=[{href:'/controle',label:'Dashboard',icon:BarChart3},{href:'/lancamentos',label:'Lançamentos',icon:ArrowDownLeft},{href:'/contas',label:'Contas',icon:Wallet},{href:'/investimentos',label:'Investimentos',icon:PiggyBank},{href:'/homologacao',label:'Homologação',icon:FileSpreadsheet}]

function normalizarValor(raw:unknown){if(typeof raw==='number')return Number.isFinite(raw)?raw:0;let t=String(raw??'').trim().replace(/R\$\s?/gi,'');if(!t)return 0;if(t.includes(','))t=t.replace(/\./g,'').replace(',','.');const n=Number(t);return Number.isFinite(n)?n:0}
function parseRows(rows:unknown[][]):Dados{const r:Dados={};const h=(rows[0]||[]).map(v=>String(v??'').trim());const idx=meses.map(m=>h.findIndex(x=>x===m));rows.slice(1).forEach(row=>{const label=String(row?.[0]??'').trim();if(!label||label==='Categoria')return;r[label]=idx.map(i=>i<0?0:normalizarValor(row?.[i]))});return r}
function parseCsv(text:string){const rows=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/).map(line=>{const d=line.includes(';')?';':',';return line.split(d).map(v=>v.trim().replace(/^\"|\"$/g,''))});return parseRows(rows)}
async function parseArquivo(file:File){const ext=file.name.toLowerCase().split('.').pop();if(ext==='xlsx'||ext==='xls'){const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false});const sheet=wb.Sheets[wb.SheetNames[0]];if(!sheet)throw new Error('Planilha sem aba válida');return parseRows(XLSX.utils.sheet_to_json(sheet,{header:1,defval:''}) as unknown[][])}if(ext==='csv')return parseCsv(await file.text());throw new Error('Formato não suportado')}

function Donut({values,total,labels}:{values:number[];total:number;labels:string[]}){const safe=values.map(v=>Math.max(0,v)),sum=safe.reduce((a,b)=>a+b,0)||1;let start=0;const colors=['#0f766e','#2b6f85','#65a9ad','#8a9aa0','#d5a14a'];const parts=safe.map((v,i)=>{const end=start+v/sum*100,p={label:labels[i],value:v,start,end,color:colors[i%colors.length]};start=end;return p});const gradient=parts.map(p=>`${p.color} ${p.start}% ${p.end}%`).join(',');return <div className="donutWrap"><div className="donut" style={{background:`conic-gradient(${gradient})`}}><div className="donutHole"><strong>{moeda(total)}</strong><span>Total</span></div></div><div className="donutLegend">{parts.map(p=><div key={p.label}><span><i style={{background:p.color}}/>{p.label}</span><b>{(p.value/sum*100).toFixed(0)}%</b></div>)}</div></div>}
function Line({values,suffix='' }:{values:number[];suffix?:string}){const series=meses.map((_,i)=>Number(values[i]??0));const w=640,h=180,p=22,max=Math.max(...series,1),min=Math.min(...series,0),range=Math.max(max-min,1),x=(i:number)=>p+i*(w-p*2)/Math.max(meses.length-1,1),y=(v:number)=>h-p-(v-min)/range*(h-p*2),points=series.map((v,i)=>`${x(i)},${y(v)}`).join(' ');return <div className="lineChartWrap"><svg viewBox={`0 0 ${w} ${h}`} className="lineChart"><line x1={p} y1={y(0)} x2={w-p} y2={y(0)} className="axis"/><polyline points={`${p},${h-p} ${points} ${w-p},${h-p}`} className="areaLine"/><polyline points={points} className="mainLine"/>{series.map((v,i)=><circle key={meses[i]} cx={x(i)} cy={y(v)} r="3.5" className="linePoint"><title>{meses[i]}: {v.toLocaleString('pt-BR',{maximumFractionDigits:2})}{suffix}</title></circle>)}</svg><div className="lineLabels">{meses.map(m=><span key={m}>{m.split('/')[0]}</span>)}</div></div>}
function MonthlyFlow({values}:{values:number[]}){const max=Math.max(...values.map(Math.abs),1);return <div style={{padding:'8px 15px 17px'}}><div style={{display:'grid',gridTemplateColumns:'repeat(12,1fr)',gap:5,height:180,alignItems:'center'}}>{values.map((v,i)=><div key={meses[i]} style={{height:'100%',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:5}}><div style={{height:145,width:'100%',position:'relative',background:'linear-gradient(to bottom,transparent 49.5%,#ccd7de 49.5%,#ccd7de 50.5%,transparent 50.5%)'}}><i style={{position:'absolute',left:'20%',right:'20%',height:`${Math.max(3,Math.abs(v)/max*45)}%`,bottom:v>=0?'50%':undefined,top:v<0?'50%':undefined,borderRadius:'3px',background:v>=0?'#4eaf88':'#e7777a'}}/></div><span style={{fontSize:9,color:'#738595'}}>{meses[i].split('/')[0]}</span></div>)}</div><div className="chartLegend"><span><i style={{background:'#4eaf88'}}/>Resultado positivo</span><span><i style={{background:'#e7777a'}}/>Resultado negativo</span></div></div>}
function Triple({receita,despesas,saldo}:{receita:number[];despesas:number[];saldo:number[]}){const max=Math.max(...receita,...despesas,...saldo.map(Math.abs),1),w=720,h=210,l=25,r=12,t=12,b=28,x=(i:number)=>l+i*(w-l-r)/11,y=(v:number)=>t+(max-v)/(max*2)*(h-t-b),zero=y(0),points=saldo.map((v,i)=>`${x(i)},${y(v)}`).join(' ');return <div style={{padding:'0 15px 15px'}}><svg viewBox={`0 0 ${w} ${h}`} style={{width:'100%',height:205}}><line x1={l} y1={zero} x2={w-r} y2={zero} className="axis"/>{meses.map((m,i)=>{const bw=12,rh=receita[i]/max*(h-t-b)/2,dh=despesas[i]/max*(h-t-b)/2;return <g key={m}><rect x={x(i)-bw-2} y={zero-rh} width={bw} height={rh} rx="2" fill="#55b990"/><rect x={x(i)+2} y={zero-dh} width={bw} height={dh} rx="2" fill="#e97a7d"/></g>})}<polyline points={points} fill="none" stroke="#1d5688" strokeWidth="2.5"/>{saldo.map((v,i)=><circle key={i} cx={x(i)} cy={y(v)} r="3.5" fill="#fff" stroke="#1d5688" strokeWidth="2"><title>{meses[i]}: {moeda(v)}</title></circle>)}</svg><div className="lineLabels">{meses.map(m=><span key={m}>{m.split('/')[0]}</span>)}</div><div className="chartLegend"><span><i className="legendIncome"/>Receita</span><span><i className="legendExpense"/>Despesas</span><span><i style={{background:'#1d5688',borderRadius:'50%'}}/>Saldo do período</span></div></div>}

export default function ControlePage(){
 const [dados,setDados]=useState<Dados>({});const [importado,setImportado]=useState(false);const [editando,setEditando]=useState<string|null>(null);const [rascunho,setRascunho]=useState<number[]>([]);const inputRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{try{const s=localStorage.getItem(STORAGE_KEY);if(s){setDados(JSON.parse(s));setImportado(true)}}catch{}})
 async function importar(file?:File){if(!file)return;try{const parsed=await parseArquivo(file);if(!Object.keys(parsed).length)throw new Error();setDados(parsed);localStorage.setItem(STORAGE_KEY,JSON.stringify(parsed));setImportado(true);setEditando(null)}catch{alert('Não foi possível importar. Selecione o modelo Excel (.xlsx/.xls) ou CSV com Jan/26 até Dez/26.')}finally{if(inputRef.current)inputRef.current.value=''}}
 const valor=(linha:string,i:number)=>Number(dados[linha]?.[i]||0)
 const receitaRows=[{label:'Salários',key:'Salários'},{label:'Férias',key:'Férias'},{label:'13º Salário',key:'13º Salário'},{label:'Bônus',key:'Bônus'},{label:'IR / Dissídio',key:'IR / Dissídio'}]
 const despesaRows=[{label:'Despesas Fixas',key:'Despesas Fixas'},{label:'Bancos e Acordos',key:'Bancos e Acordos'},{label:'Ajuste',key:'Ajuste Despesas Totais'}]
 const receitaMensal=meses.map((_,i)=>receitaRows.reduce((s,r)=>s+valor(r.key,i),0));const despesasMensal=meses.map((_,i)=>despesaRows.reduce((s,r)=>s+valor(r.key,i),0));const fluxoPeriodo=meses.map((_,i)=>receitaMensal[i]-despesasMensal[i]);const fluxoAcumulado=fluxoPeriodo.reduce<number[]>((a,v)=>{a.push((a[a.length-1]||0)+v);return a},[]);const compromisso=meses.map((_,i)=>receitaMensal[i]>0?despesasMensal[i]/receitaMensal[i]*100:0)
 const anual=useMemo(()=>({renda:receitaMensal.reduce((s,v)=>s+v,0),despesas:despesasMensal.reduce((s,v)=>s+v,0),periodo:fluxoPeriodo.reduce((s,v)=>s+v,0),fluxo:fluxoAcumulado.at(-1)||0}),[dados]);const compromissoMedio=anual.renda?anual.despesas/anual.renda*100:0
 const melhor=fluxoPeriodo.reduce((a,v,i)=>v>a.v?{v,i}:a,{v:-Infinity,i:0});const pior=fluxoPeriodo.reduce((a,v,i)=>v<a.v?{v,i}:a,{v:Infinity,i:0});const pico=compromisso.reduce((a,v,i)=>v>a.v?{v,i}:a,{v:-Infinity,i:0});const primeiro=fluxoPeriodo.slice(0,6).reduce((s,v)=>s+v,0),segundo=fluxoPeriodo.slice(6).reduce((s,v)=>s+v,0)
 const receitaComp=receitaRows.map(r=>receitaMensal.reduce((s,_,i)=>s+valor(r.key,i),0));const despesaComp=despesaRows.map(r=>despesasMensal.reduce((s,_,i)=>s+valor(r.key,i),0))
 function iniciar(key:string){setEditando(key);setRascunho(meses.map((_,i)=>valor(key,i)))}function alterar(i:number,raw:string){setRascunho(p=>{const n=[...p];n[i]=normalizarValor(raw);return n})}function salvar(){if(!editando)return;const next={...dados,[editando]:rascunho.map(v=>Math.round(v*100)/100)};setDados(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setEditando(null);setRascunho([])}function cancelar(){setEditando(null);setRascunho([])}
 function cells(key:string){return meses.map((m,i)=><td key={m} className="monthlyCell">{editando===key?<input aria-label={`${key} ${m}`} type="number" step="0.01" value={rascunho[i]??0} onChange={e=>alterar(i,e.target.value)}/>:moeda(valor(key,i))}</td>)}function action(key:string,label:string){return <td className="actionCell">{editando===key?<div className="actionButtons"><button className="saveButton" onClick={salvar} title="Salvar"><Save size={13}/></button><button className="cancelButton" onClick={cancelar} title="Cancelar"><X size={13}/></button></div>:<button className="editButton" onClick={()=>iniciar(key)} title={`Editar ${label}`}><Pencil size={13}/>Editar</button>}</td>}
 const detail=(r:{label:string;key:string})=><tr key={r.key}><td className="detailLabel"><span>{r.label}</span></td>{cells(r.key)}{action(r.key,r.label)}</tr>
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brandMark">R$</div><div><strong>Orçamento</strong><span>Familiar</span></div></div><nav>{nav.map(n=>{const I=n.icon;return <Link key={n.href} href={n.href} className={n.href==='/controle'?'active':''}><I size={17}/>{n.label}</Link>})}</nav><div className="sideBottom"><small>VISÃO EXECUTIVA</small><p>Indicadores financeiros da família em uma visão simples e objetiva.</p></div></aside><main className="content">
 <header className="top"><div><p className="eyebrow">ORÇAMENTO FAMILIAR</p><h1>Dashboard financeiro</h1><p className="muted">Visão sintética da situação financeira · 2026</p></div><div className="topActions"><button className="statusPill" onClick={()=>inputRef.current?.click()}><Upload size={14}/>{importado?'Atualizar base':'Carregar base'}</button><input ref={inputRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e=>importar(e.target.files?.[0])}/></div></header>
 {!importado&&<section className="panel" style={{marginBottom:18}}><div className="panelHead"><div><h2>Base financeira ainda não carregada</h2><p>Importe sua base para visualizar os indicadores. Os dados ficam somente neste navegador.</p></div><button className="primary" onClick={()=>inputRef.current?.click()}><Upload size={16}/>Importar Excel/CSV</button></div></section>}
 <section className="cards controlCards" style={{gridTemplateColumns:'repeat(5,minmax(0,1fr))'}}><article><div className="cardIcon income"><Users size={19}/></div><div><span>Receita Familiar</span><strong>{moeda(anual.renda)}</strong><small>Salários e recebíveis · 2026</small></div></article><article><div className="cardIcon expense"><Wallet size={19}/></div><div><span>Despesas Totais</span><strong>{moeda(anual.despesas)}</strong><small>Fixas + Bancos + Ajuste</small></div></article><article><div className="cardIcon balance"><BarChart3 size={19}/></div><div><span>Fluxo do Período</span><strong>{moeda(anual.periodo)}</strong><small>Soma dos resultados mensais</small></div></article><article><div className="cardIcon balance"><TrendingUp size={19}/></div><div><span>Fluxo de Caixa</span><strong>{moeda(anual.fluxo)}</strong><small>Saldo acumulado até Dez/26</small></div></article><article><div className="cardIcon"><Percent size={19}/></div><div><span>Comprometimento</span><strong>{pct(compromissoMedio)}</strong><small>Despesas ÷ Receita · anual</small></div></article></section>
 <section className="infoGrid"><article className="panel chartPanel"><div className="panelHead"><div><h2>Receita × Despesas × Saldo</h2><p>Visão consolidada dos 12 meses</p></div></div><Triple receita={receitaMensal} despesas={despesasMensal} saldo={fluxoPeriodo}/></article><article className="panel chartPanel"><div className="panelHead"><div><h2>Composição da Receita</h2><p>Salários e recebíveis</p></div></div><Donut values={receitaComp} total={anual.renda} labels={receitaRows.map(r=>r.label)}/></article><article className="panel chartPanel"><div className="panelHead"><div><h2>Composição das Despesas</h2><p>Despesas Totais</p></div></div><Donut values={despesaComp} total={anual.despesas} labels={despesaRows.map(r=>r.label)}/></article></section>
 <section className="panel wideChart"><div className="panelHead"><div><h2>Evolução do Fluxo de Caixa (Acumulado)</h2><p>Saldo acumulado mês a mês a partir do Fluxo de Caixa do Período</p></div><strong className="chartHighlight">{moeda(anual.fluxo)} acumulado</strong></div><Line values={fluxoAcumulado}/></section>
 <section className="infoGrid"><article className="panel chartPanel"><div className="panelHead"><div><h2>Evolução do Comprometimento da Renda</h2><p>Despesas Totais ÷ Receita Familiar</p></div></div><Line values={compromisso} suffix="%"/></article><article className="panel chartPanel"><div className="panelHead"><div><h2>Fluxo de Caixa Mensal</h2><p>Resultado de cada mês</p></div></div><MonthlyFlow values={fluxoPeriodo}/></article><article className="panel chartPanel"><div className="panelHead"><div><h2>Principais insights</h2><p>Leitura executiva da evolução</p></div></div><div style={{padding:'4px 18px 18px',display:'grid',gap:11,fontSize:11,color:'#536b7d'}}><div><Lightbulb size={14} style={{verticalAlign:'middle',marginRight:7,color:'#17825f'}}/>Melhor resultado: <b>{meses[melhor.i]}</b>, {moeda(melhor.v)}.</div><div><TrendingDown size={14} style={{verticalAlign:'middle',marginRight:7,color:'#bd5058'}}/>Maior consumo de caixa: <b>{meses[pior.i]}</b>, {moeda(pior.v)}.</div><div><Percent size={14} style={{verticalAlign:'middle',marginRight:7,color:'#25688e'}}/>Pico de comprometimento: <b>{meses[pico.i]}</b>, {pct(pico.v)}.</div><div><TrendingUp size={14} style={{verticalAlign:'middle',marginRight:7,color:'#17825f'}}/>2º semestre: <b>{segundo>=primeiro?'resultado melhor':'resultado menor'}</b> que o 1º semestre.</div></div></article></section>
 <section className="panel monthlyPanel"><div className="panelHead"><div><h2>Indicadores financeiros</h2><p>Valores em Reais (R$) · Jan/26 a Dez/26 · subtotais recalculados automaticamente</p></div></div><div className="tableWrap"><table className="monthlyTable"><thead><tr><th>Indicador</th>{meses.map(m=><th key={m}>{m}</th>)}<th>Ações</th></tr></thead><tbody>
 <tr className="sectionRow incomeRow"><td className="sectionLabel"><Users size={21}/><strong>Salários e recebíveis</strong></td>{meses.map((m,i)=><td key={m}>{moeda(receitaMensal[i])}</td>)}<td className="sectionAction">—</td></tr>{receitaRows.map(detail)}
 <tr className="sectionRow expenseRow"><td className="sectionLabel"><Wallet size={21}/><strong>Despesas Totais</strong></td>{meses.map((m,i)=><td key={m}>{moeda(despesasMensal[i])}</td>)}<td className="sectionAction">—</td></tr>{despesaRows.map(detail)}
 <tr className="sectionRow flowRow"><td className="sectionLabel"><TrendingUp size={21}/><strong>Fluxo de Caixa</strong></td>{meses.map((m,i)=><td key={m}>{moeda(fluxoAcumulado[i])}</td>)}<td className="sectionAction">—</td></tr>
 <tr className="sectionRow periodRow"><td className="sectionLabel"><BarChart3 size={21}/><strong>Fluxo de Caixa do Período</strong></td>{meses.map((m,i)=><td key={m}>{moeda(fluxoPeriodo[i])}</td>)}<td className="sectionAction">—</td></tr>
 <tr className="sectionRow commitmentRow"><td className="sectionLabel"><Percent size={21}/><strong>Comprometimento da Renda</strong></td>{meses.map((m,i)=><td key={m}>{pct(compromisso[i])}</td>)}<td className="sectionAction">—</td></tr>
 </tbody></table></div><p className="tableNote">As linhas detalhadas podem ser ajustadas manualmente. <b>Salários e recebíveis = Salários + Férias + 13º Salário + Bônus + IR / Dissídio.</b> <b>Despesas Totais = Despesas Fixas + Bancos e Acordos + Ajuste.</b> Despesas Diversas permanecem fora desse subtotal. O Fluxo de Caixa do Período é mensal; o Fluxo de Caixa é o saldo acumulado desses períodos.</p></section>
 <section className="panel"><div className="panelHead"><div><h2>Análise detalhada</h2><p>Conta, fornecedor, categoria e lançamento ficam na segunda tela.</p></div><Link className="primary" href="/lancamentos">Abrir lançamentos →</Link></div></section>
 </main></div>
}
