'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, CalendarDays, ChevronLeft, ChevronRight, CircleDollarSign, LayoutDashboard, Pencil, Plus, Receipt, Trash2, Wallet, X, ArrowRightLeft, Target } from 'lucide-react'

type Account={id:number;name:string;type:string;initialBalance:number}
type Transaction={id:number;type:'in'|'out';title:string;category:string;date:string;value:number;accountId:number}
type Transfer={id:number;title:string;date:string;value:number;fromId:number;toId:number}
type Budget={id:number;category:string;limit:number}

const initialAccounts:Account[]=[{id:1,name:'Conta Corrente',type:'Conta bancária',initialBalance:0},{id:2,name:'Poupança',type:'Reserva',initialBalance:0},{id:3,name:'Investimentos',type:'Investimentos',initialBalance:0}]
const initial:Transaction[]=[{id:1,type:'in',title:'Salário',category:'Salário',date:'2026-09-05',value:8500,accountId:1},{id:2,type:'in',title:'Rendimento',category:'Investimentos',date:'2026-09-08',value:420,accountId:3},{id:3,type:'out',title:'Supermercado',category:'Alimentação',date:'2026-09-06',value:680,accountId:1},{id:4,type:'out',title:'Escola',category:'Educação',date:'2026-09-07',value:950,accountId:1},{id:5,type:'out',title:'Combustível',category:'Transporte',date:'2026-09-08',value:320,accountId:1}]
const initialBudgets:Budget[]=[{id:1,category:'Alimentação',limit:1500},{id:2,category:'Educação',limit:1200},{id:3,category:'Transporte',limit:800},{id:4,category:'Moradia',limit:2000},{id:5,category:'Lazer',limit:600},{id:6,category:'Saúde',limit:500}]
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const dateBR=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})
export default function Home(){
 const[items,setItems]=useState<Transaction[]>(initial),[accounts,setAccounts]=useState<Account[]>(initialAccounts),[transfers,setTransfers]=useState<Transfer[]>([]),[budgets,setBudgets]=useState<Budget[]>(initialBudgets)
 const[modal,setModal]=useState(false),[editing,setEditing]=useState<Transaction|null>(null),[type,setType]=useState<'in'|'out'>('out'),[title,setTitle]=useState(''),[category,setCategory]=useState(''),[value,setValue]=useState(''),[date,setDate]=useState('2026-09-09'),[accountId,setAccountId]=useState(1)
 const[filter,setFilter]=useState<'all'|'in'|'out'>('all'),[search,setSearch]=useState(''),[month,setMonth]=useState('2026-09'),[accountModal,setAccountModal]=useState(false),[accountName,setAccountName]=useState(''),[accountType,setAccountType]=useState('Conta bancária'),[accountInitial,setAccountInitial]=useState('')
 const[transferModal,setTransferModal]=useState(false),[fromId,setFromId]=useState(1),[toId,setToId]=useState(2),[transferValue,setTransferValue]=useState(''),[transferDate,setTransferDate]=useState('2026-09-09')
 const[budgetModal,setBudgetModal]=useState(false),[budgetCategory,setBudgetCategory]=useState(''),[budgetLimit,setBudgetLimit]=useState('')
 useEffect(()=>{try{const s=localStorage.getItem('orcamento-familiar-transactions');if(s)setItems(JSON.parse(s).map((i:Transaction)=>({...i,accountId:i.accountId||1})));const a=localStorage.getItem('orcamento-familiar-accounts');if(a)setAccounts(JSON.parse(a));const t=localStorage.getItem('orcamento-familiar-transfers');if(t)setTransfers(JSON.parse(t));const b=localStorage.getItem('orcamento-familiar-budgets');if(b)setBudgets(JSON.parse(b))}catch{}},[])
 useEffect(()=>{try{localStorage.setItem('orcamento-familiar-transactions',JSON.stringify(items));localStorage.setItem('orcamento-familiar-accounts',JSON.stringify(accounts));localStorage.setItem('orcamento-familiar-transfers',JSON.stringify(transfers));localStorage.setItem('orcamento-familiar-budgets',JSON.stringify(budgets))}catch{}},[items,accounts,transfers,budgets])
 const monthItems=useMemo(()=>items.filter(i=>i.date.startsWith(month)),[items,month]);const monthTransfers=useMemo(()=>transfers.filter(t=>t.date.startsWith(month)),[transfers,month])
 const totals=useMemo(()=>{const ins=monthItems.filter(i=>i.type==='in').reduce((s,i)=>s+i.value,0),outs=monthItems.filter(i=>i.type==='out').reduce((s,i)=>s+i.value,0);return{ins,outs,balance:ins-outs}},[monthItems])
 const visibleItems=useMemo(()=>monthItems.filter(i=>{const ok=filter==='all'||i.type===filter,q=search.trim().toLowerCase();return ok&&(!q||`${i.title} ${i.category}`.toLowerCase().includes(q))}).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id),[monthItems,filter,search])
 const biggestCategory=useMemo(()=>{const m:Record<string,number>={};monthItems.filter(i=>i.type==='out').forEach(i=>m[i.category]=(m[i.category]||0)+i.value);return Object.entries(m).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—'},[monthItems])
 const accountTotals=useMemo(()=>accounts.map(a=>{const tx=items.filter(i=>i.accountId===a.id).reduce((s,i)=>s+(i.type==='in'?i.value:-i.value),0);const tr=transfers.reduce((s,t)=>s+(t.fromId===a.id?-t.value:t.toId===a.id?t.value:0),0);return{...a,current:a.initialBalance+tx+tr}}),[accounts,items,transfers])
 const budgetRows=useMemo(()=>budgets.map(b=>{const spent=monthItems.filter(i=>i.type==='out'&&i.category.toLowerCase()===b.category.toLowerCase()).reduce((s,i)=>s+i.value,0);const pct=b.limit?spent/b.limit*100:0;return{...b,spent,remaining:b.limit-spent,pct}}),[budgets,monthItems])
 const chart=useMemo(()=>{const[y,m]=month.split('-').map(Number),days=new Date(y,m,0).getDate();let bal=0;const points:number[]=[];for(let d=1;d<=days;d++){const key=`${month}-${String(d).padStart(2,'0')}`;monthItems.filter(i=>i.date===key).forEach(i=>bal+=i.type==='in'?i.value:-i.value);points.push(bal)}const hi=Math.max(...points,0),lo=Math.min(...points,0),range=hi-lo||1;return{days,coords:points.map((v,i)=>`${(i/(days-1))*100},${8+((hi-v)/range)*82}`).join(' '),balance:points.at(-1)||0}},[month,monthItems])
 const monthLabel=new Date(`${month}-01T12:00:00`).toLocaleDateString('pt-BR',{month:'long',year:'numeric'});const changeMonth=(d:number)=>{const x=new Date(`${month}-01T12:00:00`);x.setMonth(x.getMonth()+d);setMonth(`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`)}
 function resetForm(){setTitle('');setCategory('');setValue('');setDate(`${month}-09`);setType('out');setAccountId(1);setEditing(null);setModal(false)}
 function openNew(){resetForm();setModal(true)};function openEdit(i:Transaction){setEditing(i);setType(i.type);setTitle(i.title);setCategory(i.category);setValue(String(i.value).replace('.',','));setDate(i.date);setAccountId(i.accountId||1);setModal(true)}
 function save(e:React.FormEvent){e.preventDefault();const n=Number(value.replace(/\./g,'').replace(',','.'));if(!title.trim()||!Number.isFinite(n)||n<=0||!date)return;if(editing)setItems(v=>v.map(i=>i.id===editing.id?{...i,type,title:title.trim(),category:category.trim()||'Outros',date,value:n,accountId}:i));else setItems(v=>[...v,{id:Date.now(),type,title:title.trim(),category:category.trim()||'Outros',date,value:n,accountId}]);resetForm()}
 function saveAccount(e:React.FormEvent){e.preventDefault();const n=Number(accountInitial.replace(/\./g,'').replace(',','.'));if(!accountName.trim()||!Number.isFinite(n)||n<0)return;setAccounts(v=>[...v,{id:Date.now(),name:accountName.trim(),type:accountType,initialBalance:n}]);setAccountName('');setAccountInitial('');setAccountModal(false)}
 function saveTransfer(e:React.FormEvent){e.preventDefault();const n=Number(transferValue.replace(/\./g,'').replace(',','.'));if(fromId===toId||!Number.isFinite(n)||n<=0||!transferDate)return;setTransfers(v=>[...v,{id:Date.now(),title:`Transferência: ${accounts.find(a=>a.id===fromId)?.name||'Origem'} → ${accounts.find(a=>a.id===toId)?.name||'Destino'}`,date:transferDate,value:n,fromId,toId}]);setTransferValue('');setTransferDate(`${month}-09`);setTransferModal(false)}
 function saveBudget(e:React.FormEvent){e.preventDefault();const n=Number(budgetLimit.replace(/\./g,'').replace(',','.'));if(!budgetCategory.trim()||!Number.isFinite(n)||n<=0)return;setBudgets(v=>{const exists=v.find(b=>b.category.toLowerCase()===budgetCategory.trim().toLowerCase());return exists?v.map(b=>b.id===exists.id?{...b,category:budgetCategory.trim(),limit:n}:b):[...v,{id:Date.now(),category:budgetCategory.trim(),limit:n}]});setBudgetCategory('');setBudgetLimit('');setBudgetModal(false)}
 function removeItem(id:number){if(window.confirm('Excluir este lançamento?'))setItems(v=>v.filter(i=>i.id!==id))}
 return <main className="app"><aside className="sidebar"><div className="brand"><div className="brandMark">$</div><div><strong>Orçamento</strong><span>Familiar</span></div></div><nav><button className="active"><LayoutDashboard size={18}/> Dashboard</button><button><Receipt size={18}/> Lançamentos</button><button><Wallet size={18}/> Contas</button><button><CalendarDays size={18}/> Fluxo de caixa</button></nav><div className="sideBottom"><small>CONTROLE FINANCEIRO</small><p>Uma visão simples do seu dinheiro.</p></div></aside>
 <section className="content"><header className="top"><div><p className="eyebrow">VISÃO GERAL</p><h1>Olá, Léo 👋</h1><p className="muted">Aqui está o resumo das suas finanças.</p></div><div className="topActions"><button className="secondary" onClick={()=>setTransferModal(true)}><ArrowRightLeft size={17}/> Transferir</button><button className="primary" onClick={openNew}><Plus size={18}/> Novo lançamento</button></div></header>
 <div className="month"><button onClick={()=>changeMonth(-1)}><ChevronLeft size={17}/></button><strong>{monthLabel.charAt(0).toUpperCase()+monthLabel.slice(1)}</strong><button onClick={()=>changeMonth(1)}><ChevronRight size={17}/></button></div>
 <div className="cards"><article><div className="cardIcon income"><ArrowDownLeft size={19}/></div><div><span>Proventos</span><strong>{money(totals.ins)}</strong><small>Entradas no mês</small></div></article><article><div className="cardIcon expense"><ArrowUpRight size={19}/></div><div><span>Despesas</span><strong>{money(totals.outs)}</strong><small>Saídas no mês</small></div></article><article><div className="cardIcon balance"><CircleDollarSign size={19}/></div><div><span>Saldo do mês</span><strong>{money(totals.balance)}</strong><small>Transferências não alteram o saldo</small></div></article></div>
 <section className="panel accountsPanel"><div className="panelHead"><div><h2>Minhas contas</h2><p>Saldo estimado por conta</p></div><div className="panelActions"><button className="linkBtn" onClick={()=>setTransferModal(true)}><ArrowRightLeft size={14}/> Transferir</button><button className="linkBtn" onClick={()=>setAccountModal(true)}><Plus size={14}/> Nova conta</button></div></div><div className="accountGrid">{accountTotals.map(a=><div className="accountCard" key={a.id}><div className="accountIcon"><Wallet size={17}/></div><div><span>{a.name}</span><small>{a.type}</small><strong>{money(a.current)}</strong></div></div>)}</div></section>
 <section className="panel budgetsPanel"><div className="panelHead"><div><h2>Orçamento por categoria</h2><p>Defina limites e acompanhe o quanto ainda pode gastar.</p></div><button className="linkBtn" onClick={()=>setBudgetModal(true)}><Target size={14}/> Definir limite</button></div><div className="budgetList">{budgetRows.map(b=><div className="budgetRow" key={b.id}><div className="budgetTop"><div><strong>{b.category}</strong><span>{money(b.spent)} de {money(b.limit)}</span></div><b className={b.pct>=100?'over':b.pct>=80?'warning':''}>{Math.round(b.pct)}%</b></div><div className="budgetTrack"><i className={b.pct>=100?'over':b.pct>=80?'warning':''} style={{width:`${Math.min(100,b.pct)}%`}}/></div><small className={b.remaining<0?'overText':''}>{b.remaining>=0?`Disponível: ${money(b.remaining)}`:`Excedido em ${money(Math.abs(b.remaining))}`}</small></div>)}</div></section>
 <div className="grid"><section className="panel chartPanel"><div className="panelHead"><div><h2>Fluxo de caixa</h2><p>Saldo acumulado por dia</p></div><span className="legend"><i/> Saldo</span></div><div className="chart"><div className="line l1"/><div className="line l2"/><div className="line l3"/><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="chartSvg"><polyline points={chart.coords} fill="none" stroke="currentColor" strokeWidth="1.8" vectorEffect="non-scaling-stroke"/></svg><div className="axis"><span>01</span><span>05</span><span>10</span><span>15</span><span>20</span><span>25</span><span>{chart.days}</span></div></div><div className="chartFoot"><span>Saldo inicial: R$ 0,00</span><strong>Saldo final: {money(chart.balance)}</strong></div></section><section className="panel"><div className="panelHead"><div><h2>Resumo</h2><p>Distribuição do mês</p></div></div><div className="summary"><div><span>Comprometido</span><strong>{totals.ins?Math.round(totals.outs/totals.ins*100):0}%</strong></div><div className="progress"><b style={{width:`${totals.ins?Math.min(100,totals.outs/totals.ins*100):0}%`}}/></div><div className="summaryRow"><span>Restante</span><strong>{money(totals.balance)}</strong></div><div className="summaryRow"><span>Maior categoria</span><strong>{biggestCategory}</strong></div><div className="summaryRow"><span>Movimentações</span><strong>{monthItems.length}</strong></div><div className="summaryRow"><span>Transferências</span><strong>{monthTransfers.length}</strong></div></div></section></div>
 <section className="panel transactions"><div className="panelHead"><div><h2>Lançamentos</h2><p>Cadastre, edite, exclua e filtre suas movimentações.</p></div><span className="count">{visibleItems.length} itens</span></div><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar lançamento..."/><div className="filterBtns"><button className={filter==='all'?'chosen':''} onClick={()=>setFilter('all')}>Todos</button><button className={filter==='in'?'chosen':''} onClick={()=>setFilter('in')}>Proventos</button><button className={filter==='out'?'chosen':''} onClick={()=>setFilter('out')}>Despesas</button></div></div>{visibleItems.length===0?<div className="empty">Nenhum lançamento encontrado neste mês.</div>:visibleItems.slice(0,10).map(i=><div className="transaction" key={i.id}><div className={`txIcon ${i.type}`}>{i.type==='in'?<ArrowDownLeft size={17}/>:<ArrowUpRight size={17}/>}</div><div className="txName"><strong>{i.title}</strong><span>{i.category} · {dateBR(i.date)} · {accounts.find(a=>a.id===i.accountId)?.name||'Conta'}</span></div><strong className={i.type==='in'?'valueIn':'valueOut'}>{i.type==='in'?'+':'-'} {money(i.value)}</strong><button className="iconBtn" onClick={()=>openEdit(i)}><Pencil size={15}/></button><button className="iconBtn danger" onClick={()=>removeItem(i.id)}><Trash2 size={15}/></button></div>)}</section></section>
 {modal&&<div className="overlay"><form className="modal" onSubmit={save}><div className="modalHead"><div><h2>{editing?'Editar lançamento':'Novo lançamento'}</h2><p>Registre uma entrada ou saída.</p></div><button type="button" onClick={resetForm}><X/></button></div><div className="typeSwitch"><button type="button" className={type==='out'?'selectedOut':''} onClick={()=>setType('out')}>Despesa</button><button type="button" className={type==='in'?'selectedIn':''} onClick={()=>setType('in')}>Provento</button></div><label>Descrição<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Mercado"/></label><label>Categoria<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Ex.: Alimentação"/></label><label>Conta<select value={accountId} onChange={e=>setAccountId(Number(e.target.value))}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><div className="two"><label>Valor<input required value={value} onChange={e=>setValue(e.target.value)} inputMode="decimal" placeholder="R$ 0,00"/></label><label>Data<input required value={date} onChange={e=>setDate(e.target.value)} type="date"/></label></div><button className="primary full">{editing?'Salvar alterações':'Salvar lançamento'}</button></form></div>}
 {accountModal&&<div className="overlay"><form className="modal" onSubmit={saveAccount}><div className="modalHead"><div><h2>Nova conta</h2><p>Cadastre uma conta ou carteira.</p></div><button type="button" onClick={()=>setAccountModal(false)}><X/></button></div><label>Nome<input required value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="Ex.: Banco Santander"/></label><label>Tipo<select value={accountType} onChange={e=>setAccountType(e.target.value)}><option>Conta bancária</option><option>Poupança</option><option>Carteira</option><option>Investimentos</option><option>Outro</option></select></label><label>Saldo inicial<input required value={accountInitial} onChange={e=>setAccountInitial(e.target.value)} inputMode="decimal" placeholder="R$ 0,00"/></label><button className="primary full">Cadastrar conta</button></form></div>}
 {transferModal&&<div className="overlay"><form className="modal" onSubmit={saveTransfer}><div className="modalHead"><div><h2>Transferir entre contas</h2><p>Movimente seu dinheiro sem contar como despesa.</p></div><button type="button" onClick={()=>setTransferModal(false)}><X/></button></div><label>Origem<select value={fromId} onChange={e=>setFromId(Number(e.target.value))}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Destino<select value={toId} onChange={e=>setToId(Number(e.target.value))}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Valor<input required value={transferValue} onChange={e=>setTransferValue(e.target.value)} inputMode="decimal" placeholder="R$ 0,00"/></label><label>Data<input required value={transferDate} onChange={e=>setTransferDate(e.target.value)} type="date"/></label><button className="primary full">Confirmar transferência</button></form></div>}
 {budgetModal&&<div className="overlay"><form className="modal" onSubmit={saveBudget}><div className="modalHead"><div><h2>Definir orçamento</h2><p>Crie ou atualize o limite mensal de uma categoria.</p></div><button type="button" onClick={()=>setBudgetModal(false)}><X/></button></div><label>Categoria<input required value={budgetCategory} onChange={e=>setBudgetCategory(e.target.value)} placeholder="Ex.: Alimentação"/></label><label>Limite mensal<input required value={budgetLimit} onChange={e=>setBudgetLimit(e.target.value)} inputMode="decimal" placeholder="R$ 1.500,00"/></label><button className="primary full">Salvar limite</button></form></div>}
 </main>}
